### ISSUE TITLE
parameter 2 and 9 are the same

### ISSUE THREAD

**Issue by yaweiw** [yaweiw/elk-acs-kubernetes-template#2]
MASTER_DNS=$1

LOCATION=$2

MASTER_USERNAME=$3

NGINX_PASSWORD=$4

BASED_PRIVATE_KEY=$5

REGISTRY_NAME=$6

REGISTRY_PASS=$7

export REGISTRY_URL=${REGISTRY_NAME}.azurecr.io

export STORAGE_ACCOUNT=$8

export STORAGE_LOCATION=$9

**Comment by zhzy0077** [comment]
#7
